services:
  postgres:
#    build:
#      context: .
#      dockerfile: docker/postgresDockerFile
    image: postgres:16.0
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:11.3.3
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:5432/appdb -user=appuser -password=apppass -connectRetries=60 -locations=filesystem:/migrations migrate
    volumes:
      - ./src/main/resources/db/migration:/migrations

volumes:
  postgres_data: